### ISSUE TITLE
Distinguish plugin discovery vs instantiation

### ISSUE THREAD

**Issue by qwcode** [manheim/eds#28]
In order to discover plugins that need to be installed, we need to support a process where plugin configurations are discovered (which includes their pip install requirements), without the plugins being instantiated, which assumes installation.

**Comment by jantman** [comment]
I'm finding the description of this issue a bit confusing?

**Comment by qwcode** [comment]
initially, the routine I wrote, was instantiating plugins using their classes during the discovery phase.  but, it can't be assumed those classes are present until the respective plugins are installed.  so, the process needs to take that into that account.  a PR is coming today to handle this.

**Comment by jantman** [comment]
Ah, right, ok. Thanks. And cool.
